server:
  port: ${peanut.server.port}

spring:
  application:
    name: peanut-chat-app

  profiles:
    active: dev

  redis:
    host: ${peanut.redis.host}
    port: ${peanut.redis.port}
    database: 0


  datasource:
    url: jdbc:mysql://${peanut.mysql.ip}:${peanut.mysql.port}/${peanut.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: ${peanut.mysql.username}
    password: ${peanut.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
  #      connection-test-query: SELECT


# RocketMq
rocketmq:
  name-server: ${peanut.rocketmq.name-server}
  producer:
    group: ${peanut.rocketmq.producer.group}



peanut:
  # WeChat
  wx:
    mp:
      callback: ${peanut.wx.callback}
      configs:
        - appId: ${peanut.wx.appId} # 第一个公众号的appid
          secret: ${peanut.wx.secret} # 公众号的appsecret
          token: ${peanut.wx.token} # 接口配置里的Token值


  # ws
  ws:
    port: ${peanut.im.ws.port}
